config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "events#index"

  resources :users
  get '/sign_in', to: 'users#sign_in_form'
  post '/sign_in', to: 'users#sign_in'
  get '/sign_out', to: 'users#sign_out'

  resources :events, only: [:new,:create,:show,:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  # has_many: user
  belongs_to :creator, class_name: 'User'
  has_many :attendees, through: :invites, source: :user
  has_many :invites

  validates :description, :date, presence: true

  scope :previous_events, ->(_time) { where('date < ?', Date.today) }
  scope :upcoming_events, ->(_time) { where('date >= ?', Date.today) }
end

app/models/invite.rb
class Invite < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: :creator_id
  has_many :invites
  has_many :attended_events, through: :invites, source: :event

  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def create
    current_user = User.find(session[:current_user_id])
    @event = current_user.events.build(event_params)
    # @event.date = 'Tomorrow'
    if @event.save
      redirect_to @event
    else
      redirect_to root_path
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def index
    @events = Event.all
    @current_user = User.find(session[:current_user_id]) unless session[:current_user_id].nil?
    @upcoming_events = Event.upcoming_events(Date.today)
    @prev_events = Event.previous_events(Date.today)
  end

  private

  def event_params
    params.require(:event).permit(:description, :location, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @users = User.all
    @user = if session[:current_user_id].nil?
              User.new
            else
              User.find(session[:current_user_id])
            end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:current_user_id] = @user.id
      redirect_to root_path
    else
      render 'new'
    end
  end

  def sign_in
    @user = User.find_by(name: params[:user][:name]) unless params[:user].nil?
    if @user
      session[:current_user_id] = @user.id
      redirect_to root_path
    else
      flash[:alert] = 'User not found.'
      @user = User.new
      render 'sign_in_form'
    end
  end

  def sign_out
    reset_session
    redirect_to root_path
    flash[:alert] = 'User Signed out Successfully'
  end

  def show
    @user = User.find(params[:id])

    @upcoming_events = []
    @previous_events = []
    future_events = Event.upcoming_events(Date.today)
    past_events = Event.previous_events(Date.today)
    @user.invites.each do |invite|
      future_event = invite.event if future_events.include?(invite.event)
      past_event = invite.event if past_events.include?(invite.event)
      @upcoming_events << future_event unless future_event.nil?
      @previous_events << past_event unless past_event.nil?
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>All Events:</h1>
<p class="flash"><%= flash.alert %></p>
<%unless session[:current_user_id].nil? %>
<h3>Welcome <%=@current_user.name%></h3>
 <%= link_to "Create Event", new_event_path%> <br>
 <%= link_to "User Profile", user_path(session[:current_user_id])%>
<% end %>

<h1>Past events</h1>
<% @prev_events.each do |event|%>
<u><%= event.creator.name %></u> <br>
 <b> <%= event.description %></b> <br> 
  <%= event.date %> <br><br>
<% end %>

<h1>Future events</h1>
<% @upcoming_events.each do |event|%>
<u><%= event.creator.name %></u> <br>
  <b><%= event.description %></b> <br> 
  <%= event.date %> <br><br>
<% end %>

<%if session[:current_user_id].nil? %>
  <%= link_to "Sign in", sign_in_path%> <br>

  <%= link_to "Sign up", new_user_path%><br>

<% else %>
  <%= link_to "Sign out", sign_out_path%><br>
<% end %>

app/views/events/new.html.erb
<h1> Events </h1>
<%= form_for(@event) do |f| %>
 <%= f.label :description, 'Adding Description' %> <br>
 <%= f.text_field :description %> <br> <br>
 <%= f.label :date, 'Adding Date for Events' %> <br>
 <%= f.text_field :date, placeholder: 'YYYY/MM/DD' %> <br> <br>
  <%= f.label :location, 'Location for Events' %> <br>
 <%= f.text_field :location, placeholder: 'Eg. USA' %> <br> 
 <br> 
 <%= f.submit %>
 
 <p class="flash"><%= flash.notice %></p>
 
<%end%>

 <%= link_to "Home", root_path%>

app/views/events/show.html.erb
<p><h2>Hi @ <%= @event.creator.name %> <br></h2>
<p>You have created the following events</p>
<h2><%= @event.description %></h2>

<p><h3>Events Date: <%= @event.date %><br>
Event location: <%= @event.location %><br></h3></p>
<% @event.invites.each do |invitation| %>
  <%= invitation.user.name %> <br>
<% end %>

 <%= link_to "Home", root_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.hml.erb
<h1> <%@user.name%> </h1>

app/views/users/index.html.erb
<% provide(:title, 'Participant List') %>
<h1>All Users </h1>
<% @users.each do |user| %>
<% link_to user.name, user %>
<%end%>

app/views/users/new.html.erb
<h1>Create a new user</h1>

<%= @users.find(session[:current_user_id]).name unless session[:current_user_id].nil? %>

<%= form_for(@user) do |f| %>
 
 <ul>
 <% @user.errors.full_messages.each do |error| %>
   <li><%= error %></li>
 <% end %>
 </ul>
 <%= f.label :name, 'Your Username here' %> <br>
 <%= f.text_field :name %> <br> <br>
 <%= f.label :email %> <br>
 <%= f.email_field :email%> <br>
 <br>
 <%= f.submit %>
 
 <p class="flash"><%= flash.notice %></p>
 
<%end%>

 <%= link_to "Home", root_path%> <br>
<%= link_to "Sign in", sign_in_path%>

app/views/users/show.html.erb
<h1>Welcome <%= @user.name %></h1>
<% if @user.events.any? %>
<h2><u>Events created</u></h2>

  <% @user.events.each do |event| %>
    <p>
     <b> <%= event.description %></b><br>
    <u>Events Date: <%= event.date %></u><br>
<i>Event location: <%= event.location %></i><br></p>
  <%end%>

<%else%>
	<h3>You have not created any events yet</h3>
<%end%>

<% if @user.invites.any? %>
	<h2><u>Invitations</u> </h2>

  <h3>Past events</h3>
  
    <% @previous_events.each do |event| %>
        <p>
     <b> <%= event.description %></b><br>
    <u>Events Date: <%= event.date %></u><br>
<i>Event location: <%= event.location %></i><br></p>
      <%end%>
  
 

  <h3>Upcomming events</h3>
    
      <% @upcoming_events.each do |event| %>
        <p>
     <b> <%= event.description %></b><br>
    <u>Events Date: <%= event.date %></u><br>
<i>Event location: <%= event.location %></i><br></p>
      <%end%>
    

<%else%>
	<h3>You have no upcomming events</h3>
<%end%>

<%= link_to "Sign out", sign_out_path%><br>
<%= link_to "Create Event", new_event_path%> <br>

app/views/users/sign_in_form.html.erb
<h1>Sign in</h1>

<%= form_for(:user, url: sign_in_path) do |f| %>
 
 <%= f.label :name, 'Your Username here' %> <br>
 <%= f.text_field :name %> <br>

<%= f.submit 'Sign in' %> <br>
 <%= link_to "Home", root_path%><br>
 <p class="flash"><%= flash.alert %></p>
 
<%end%>